### PR TITLE
Unit tests for verifying imports

### PR DESCRIPTION
**Pull request by GhaziSyed**
added a script that runs unit tests to see 
-if library imports of fmperf are working 
-if kuberenets import is working
-if k8 python client is working
-also added a github action workflow to automate the testing upon push and pull request

### CODE REVIEW

**Comment by tdoublep** [comment]
@GhaziSyed The diff still looks bigger than it should. Could you please try to merge/rebase against latest changes on main. It should be enough to hit the "Update branch" button on github.

**Comment by GhaziSyed** [comment]
> @GhaziSyed The diff still looks bigger than it should. Could you please try to merge/rebase against latest changes on main. It should be enough to hit the "Update branch" button on github.

**Comment by tdoublep** [comment]
Is there a reason you closed the PR?

**Comment by GhaziSyed** [comment]
Clicking the update button did update the branch but then closed the PR automatically for some reason.

I also noticed the file tests\test_imports.py file wrongly committed which I also want to remove. 
I will work on creating a new PR, as git checkout ghs-tests -- tests/test_imports.py does not remove the file from git.

**Comment by tdoublep** [comment]
I don't think there is any need to create a new PR - you should just be able to re-open this one? 

>I also noticed the file tests\test_imports.py file wrongly committed which I also want to remove.
I will work on creating a new PR, as git checkout ghs-tests -- tests/test_imports.py does not remove the file from git.

That is not the correct command to remove a file from git, you are looking for:
```
git rm tests/test_imports.py
``

**Comment by GhaziSyed** [comment]
Thanks. 
The branch seems ready now

**Review by tdoublep — APPROVED** [review]
LGTM

**Pull request merged**
