### PR TITLE
Move the imports of the tgis grpc stubs to where they are used

### PR DESCRIPTION
**Pull request by maxdebayser**
With this change we can run with the vLLM backend without having to install this dependency.

### CODE REVIEW

**Comment by maxdebayser** [comment]
cc: @tdoublep

**Review by tdoublep — APPROVED** [review]
LGTM

**Comment by maxdebayser** [comment]
Actually the I'm no longer sure if this PR makes sense because there is a dependency on the `approx` module that is used in both cases. Or maybe we could copy this module to this repo.

**Comment by tdoublep** [comment]
> Actually the I'm no longer sure if this PR makes sense because there is a dependency on the `approx` module that is used in both cases. Or maybe we could copy this module to this repo.

Ah right. Maybe we could just copy it yeah

**Comment by maxdebayser** [comment]
> Ah right. Maybe we could just copy it yeah

Done

**Pull request merged**
